/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "eu-west-1:0b3d8944-ca1a-4433-9d92-c92e083249f7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_CnG6k99Zu",
    "aws_user_pools_web_client_id": "50edbppliai24crhetulf4ub9c",
    "oauth": {}
};


export default awsmobile;
